-- Setting BatonRequired flag for All Variants starting from v1-330

-- Setting Old Variants, All were set to True
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=330
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=331
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=332
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=333
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=334
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=335
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=336
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=337
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=338
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=339
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=340
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=341
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=342
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=343
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=350
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=351
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=352
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=353
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=354
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=355
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=356
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=357
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=361
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=362
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=363
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=364
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=365
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=366
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=367
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=368
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=369
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=370
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=371
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=372
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=373
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=374
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=378
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=380
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=381
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=382
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=383
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=384
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=385
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=386
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=387
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=388
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=389
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=390
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=391
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=392
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=393
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=405
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=406
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=407
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=408
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=409
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=410
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=411
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=412
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=413
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=414
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=415
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=416
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=417

-- New Starz Variants
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=418
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=419
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=420
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=421
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=422
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=423
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=424
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=425
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=426
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=427
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=500
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=501
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=502
Update ALStreamSourceConfiguration Set BatonRequired=0 Where VariantId=503
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=2000
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=2001
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=2002
Update ALStreamSourceConfiguration Set BatonRequired=1 Where VariantId=2003
